---
version: '3'
services:
    elasticsearch:
        container_name: microcosm_elasticsearch
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            bootstrap.memory_lock: 'true'
            cluster.name: docker-cluster
            http.host: 0.0.0.0
            transport.host: 127.0.0.1
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        ports:
        - 9200:9200
